---
name: Integrate

on: push

concurrency:
    group: deploy-workflow-${{ !contains( github.ref_name, fromJson('["master", "staging", "release"]') ) && github.ref || github.run_number }}
    cancel-in-progress: true

jobs:
    interrogate:
        runs-on: self-hosted
        timeout-minutes: 20
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Run interrogate docstring coverage
              uses: JackMcKew/python-interrogate-check@v0.1.1
              with:
                  path: src
                  fail-under: 80

    pytest:
        runs-on: self-hosted
        container:
            image: python:3.9
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Install requirements
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r test-requirements.txt
              env:
                  GITHUB_TOKEN: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
                  BUCKET_URL: ${{ secrets.BUCKET_URL }}
                  DEFAULT_OBJECT_NAME: ${{ secrets.DEFAULT_OBJECT_NAME }}
            - name: Run tests
              run: |
                  export PYTHONPATH=./src:./tests
                  python -m pytest ./tests -v --cov=. --cov-report term --cov-report xml:coverage-reports/coverage.xml
                  coverage xml -i


    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: psf/black@stable
              with:
                  src: ./src
                  jupyter: true
